var WI_CACHE_KEY="webCache", WI_SET_KEY="webintel";
function wiSettings(){var KS=window.KlirStore;if(!KS.S[WI_SET_KEY])KS.S[WI_SET_KEY]={enabled:true,domainCheck:true,cacheHours:24,maxBatch:100,timeoutMs:12000};return KS.S[WI_SET_KEY];}
function wiCache(){var KS=window.KlirStore;if(!KS.S[WI_CACHE_KEY])KS.S[WI_CACHE_KEY]={};return KS.S[WI_CACHE_KEY];}
function wiCleanDomain(d){return window.KlirSecurity.domain(d);}
function wiProspectDomain(p){return wiCleanDomain(p.domain||p.website||"");}
function wiEnsure(p){if(p.website_url===undefined)p.website_url=p.website||"";if(p.website_status===undefined)p.website_status="UNKNOWN";if(p.website_http_status===undefined)p.website_http_status=null;if(p.website_https===undefined)p.website_https=null;if(p.website_redirect_url===undefined)p.website_redirect_url="";if(p.website_last_checked===undefined)p.website_last_checked="";if(p.domain_name===undefined)p.domain_name=wiProspectDomain(p);if(p.domain_status===undefined)p.domain_status="UNKNOWN";if(p.domain_source===undefined)p.domain_source="";if(p.domain_last_checked===undefined)p.domain_last_checked="";if(p.dns_status===undefined)p.dns_status="UNKNOWN";if(p.ssl_status===undefined)p.ssl_status="UNKNOWN";if(p.website_confidence===undefined)p.website_confidence=0;if(p.domain_confidence===undefined)p.domain_confidence=0;if(!Array.isArray(p.signals))p.signals=[];return p;}
function wiBadgeSite(p){wiEnsure(p);var m={ACTIVE:"🟢 ACTIVE",INACTIVE:"🟠 SITE INACTIVE",REGISTERED_INACTIVE:"🟠 SITE INACTIVE",AVAILABLE:"🔴 DOMAIN AVAILABLE",UNKNOWN:"⚪ UNKNOWN"};return m[p.website_status]||"⚪ UNKNOWN";}
function wiBadgeDomain(p){wiEnsure(p);var m={REGISTERED:"🟢 REGISTERED",AVAILABLE:"🔴 AVAILABLE",UNKNOWN:"⚪ UNKNOWN"};return m[p.domain_status]||"⚪ UNKNOWN";}
function wiDigitalOpp(p){wiEnsure(p);if(!p.domain_name)return {level:"LOW",why:"aucun domaine renseigné"};if(p.website_status==="AVAILABLE"||p.domain_status==="AVAILABLE")return {level:"HIGH",why:"domaine potentiellement disponible (à vérifier manuellement)"};if(p.website_status==="INACTIVE"||p.website_status==="REGISTERED_INACTIVE")return {level:p.domain_status==="REGISTERED"?"HIGH":"MEDIUM",why:"domaine enregistré mais aucun site web actif détecté lors de la dernière vérification"};if(p.website_https===false)return {level:"MEDIUM",why:"HTTPS non détecté"};if(p.website_status==="UNKNOWN")return {level:"LOW",why:"statut invérifiable — vérification manuelle requise"};return {level:"LOW",why:"site actif détecté"};}
function wiAddSignals(p){wiEnsure(p);var add=[];if(!p.domain_name)return [];if(p.website_status==="INACTIVE"||p.website_status==="REGISTERED_INACTIVE")add.push("🌐 No active website detected");if(p.website_http_status&&p.website_http_status>=500)add.push("⚠️ Website unreachable");if(p.website_https===false&&p.website_status==="ACTIVE")add.push("🔐 HTTPS unavailable");if((p.website_status==="INACTIVE"||p.website_status==="REGISTERED_INACTIVE")&&p.domain_status==="REGISTERED")add.push("🌐 Domain registered but website inactive");for(const s of add)if(!p.signals.includes(s))p.signals.push(s);return add;}
async function wiFetch(url,ms){var parsed=new URL(url);if(parsed.protocol!=="https:"||(!window.KlirSecurity.domain(parsed.hostname)&&!["dns.google","rdap.org","rdap.verisign.com","rdap.ca.fury.ca"].includes(parsed.hostname)))throw new Error("destination-refused");var ctrl=new AbortController();var t=setTimeout(()=>ctrl.abort(),ms||12000);try{return await fetch(parsed.href,{signal:ctrl.signal,credentials:"omit",redirect:"error",referrerPolicy:"no-referrer"});}finally{clearTimeout(t);}}
async function wiDnsHas(domain){try{var r=await (await fetch("https://dns.google/resolve?name="+encodeURIComponent(domain)+"&type=A")).json();return !!(r.Answer&&r.Answer.length);}catch(e){return null;}}
function wiRdapUrl(domain){var tld=domain.split(".").pop();if(tld==="com"||tld==="net")return "https://rdap.verisign.com/"+tld+"/v1/domain/"+domain;if(tld==="ca")return "https://rdap.ca.fury.ca/rdap/domain/"+domain;return "https://rdap.org/domain/"+domain;}
async function wiRdap(domain,ms){try{var r=await wiFetch(wiRdapUrl(domain),ms);if(r.status===404)return {exists:false,source:wiRdapUrl(domain)};if(!r.ok)return {exists:null,source:wiRdapUrl(domain)};var j=await r.json().catch(()=>null);if(j&&(j.handle||j.ldhName||j.status))return {exists:true,source:wiRdapUrl(domain)};return {exists:null,source:wiRdapUrl(domain)};}catch(e){return {exists:null,source:"",error:String(e&&e.message||e)}}}
async function wiHttpTry(domain,ms){var out={https:null,http:null,redirect:"",code:null};if(!wiCleanDomain(domain))return out;try{var r=await wiFetch("https://"+domain,ms);out.https=true;out.code=r.status;return out;}catch(e){out.https=false;return out;}}
async function wiCheckDomain(domain,opts){domain=wiCleanDomain(domain);opts=opts||{};var cfg=wiSettings(),now=new Date().toISOString();if(!domain)return {domain_name:"",website_url:"",website_status:"UNKNOWN",website_http_status:null,website_https:null,website_redirect_url:"",website_last_checked:now,domain_status:"UNKNOWN",domain_source:"",domain_last_checked:now,dns_status:"UNKNOWN",ssl_status:"UNKNOWN",website_confidence:10,domain_confidence:10};var c=wiCache();var cached=c[domain];if(!opts.force&&cached&&(Date.now()-(cached.at||0))<cfg.cacheHours*3600*1000)return cached.res;
var res={domain_name:domain,website_url:"https://"+domain,website_status:"UNKNOWN",website_http_status:null,website_https:null,website_redirect_url:"",website_last_checked:now,domain_status:"UNKNOWN",domain_source:"",domain_last_checked:now,dns_status:"UNKNOWN",ssl_status:"UNKNOWN",website_confidence:50,domain_confidence:50};
var dns=await wiDnsHas(domain);res.dns_status=dns===true?"CONFIGURED":dns===false?"MISSING":"UNKNOWN";
var http=await wiHttpTry(domain,cfg.timeoutMs);res.website_http_status=http.code;res.website_https=http.https===true?true:(http.https===false&&http.http===true?false:null);res.website_redirect_url=http.redirect||"";res.ssl_status=http.https===true?"VALID":(http.https===false?"MISSING":"UNKNOWN");
if(http.code&&http.code<400){res.website_status="ACTIVE";res.website_confidence=96;}
else if(http.code===403){res.website_status="ACTIVE";res.website_confidence=80;}
else if(http.code===404){res.website_status="INACTIVE";res.website_confidence=75;}
else if(http.code&&http.code>=500){res.website_status="INACTIVE";res.website_confidence=65;}
else{res.website_status="UNKNOWN";res.website_confidence=40;}
var rdap={exists:null};if(cfg.domainCheck){rdap=await wiRdap(domain,cfg.timeoutMs);res.domain_source=rdap.source||"";}
if(rdap.exists===true){res.domain_status="REGISTERED";res.domain_confidence=95;if(res.website_status==="UNKNOWN"&&dns===true){res.website_status="REGISTERED_INACTIVE";res.website_confidence=70;}}
else if(rdap.exists===false){res.domain_status="AVAILABLE";res.domain_confidence=90;res.website_status="AVAILABLE";res.website_confidence=85;}
else{res.domain_status="UNKNOWN";res.domain_confidence=40;}
if(res.website_status==="REGISTERED_INACTIVE"&&res.domain_status==="UNKNOWN"&&dns===true){res.domain_status="REGISTERED";res.domain_confidence=70;res.domain_source=res.domain_source||"DNS";}
c[domain]={at:Date.now(),res:res};var keys=Object.keys(c);if(keys.length>500)delete c[keys[0]];try{window.KlirStore.save();}catch(e){}
return res;}
async function wiCheckProspect(p,opts){wiEnsure(p);var d=wiProspectDomain(p);if(!d){p.website_status="UNKNOWN";p.domain_status="UNKNOWN";p.website_confidence=10;p.domain_confidence=10;return p;}var r=await wiCheckDomain(d,opts);p.website_url=r.website_url;p.website_status=r.website_status;p.website_http_status=r.website_http_status;p.website_https=r.website_https;p.website_redirect_url=r.website_redirect_url;p.website_last_checked=r.website_last_checked.slice(0,16).replace("T"," — ");p.domain_name=r.domain_name;p.domain_status=r.domain_status;p.domain_source=r.domain_source;p.domain_last_checked=r.domain_last_checked.slice(0,16).replace("T"," — ");p.dns_status=r.dns_status;p.ssl_status=r.ssl_status;p.website_confidence=r.website_confidence;p.domain_confidence=r.domain_confidence;wiAddSignals(p);try{window.KlirStore.save();}catch(e){}return p;}
async function wiBulkCheck(ids,opts){opts=opts||{};var cfg=wiSettings();ids=(ids||[]).slice(0,cfg.maxBatch);var done=0,stats={active:0,inactive:0,available:0,unknown:0};var queue=[...ids];async function worker(){while(queue.length){var id=queue.shift();var p=window.KlirStore.S.prospects.find(x=>x.id===id);if(p){try{await wiCheckProspect(p,{force:!!opts.force});}catch(e){wiEnsure(p);}}done++;var pp=p?window.KlirStore.S.prospects.find(x=>x.id===id):null;var st=pp?pp.website_status:"UNKNOWN";if(st==="ACTIVE")stats.active++;else if(st==="INACTIVE"||st==="REGISTERED_INACTIVE")stats.inactive++;else if(st==="AVAILABLE")stats.available++;else stats.unknown++;if(opts.onProgress){try{opts.onProgress(done,ids.length,stats);}catch(e){}}}}var workers=[];for(var i=0;i<4;i++)workers.push(worker());await Promise.all(workers);try{var S=window.KlirStore.S;S.webintelStats={at:new Date().toLocaleString(),checked:done,active:stats.active,inactive:stats.inactive,available:stats.available,unknown:stats.unknown};window.KlirStore.save();window.KlirStore.audit("webintel.bulk",done+" domaines");}catch(e){}return stats;}
function wiParseFilter(q){q=String(q||"").toLowerCase();var f={};if(/sans site|sans site web|pas de site|no website|without website|mauvaise presence|poor web presence/.test(q))f.noSite=true;if(/site inactif|website inactive|site inaccessible/.test(q))f.webInactive=true;if(/domaine enregistre.*inactif|registered.*inactive|domaine.*mais.*site/.test(q))f.regInactive=true;if(/domaine disponible|domain available/.test(q))f.domainAvailable=true;if(/domaine enregistre|domain registered/.test(q))f.domainRegistered=true;if(/https|securise|ssl/.test(q)&&/probleme|issue|unavailable|manquant|sans/.test(q))f.httpsIssue=true;if(/site actif|website active|avec site/.test(q))f.webActive=true;return f;}
function wiMatch(p,f){if(!f||!Object.keys(f).length)return true;wiEnsure(p);if(f.noSite&&(p.website_status==="ACTIVE"))return false;if(f.noSite&&!(p.website_status==="INACTIVE"||p.website_status==="REGISTERED_INACTIVE"||p.website_status==="AVAILABLE"||p.website_status==="UNKNOWN"||!p.domain_name))return false;if(f.webInactive&&!(p.website_status==="INACTIVE"||p.website_status==="REGISTERED_INACTIVE"))return false;if(f.webActive&&p.website_status!=="ACTIVE")return false;if(f.regInactive&&!((p.website_status==="INACTIVE"||p.website_status==="REGISTERED_INACTIVE")&&p.domain_status==="REGISTERED"))return false;if(f.domainAvailable&&p.domain_status!=="AVAILABLE")return false;if(f.domainRegistered&&p.domain_status!=="REGISTERED")return false;if(f.httpsIssue&&!(p.website_https===false))return false;return true;}
function wiDrawerHTML(p){wiEnsure(p);var opp=wiDigitalOpp(p);var domSrc="";if(p.domain_source){var h=p.domain_source.split("/")[2]||p.domain_source;domSrc=" <small>(Verified using: "+h.slice(0,40)+")</small>";}var httpsLine=p.website_https===true?"✓ Enabled":(p.website_https===false?"✕ Unavailable":"— non vérifié");var dnsLine=p.dns_status==="CONFIGURED"?"✓ Configured":(p.dns_status==="MISSING"?"✕ Missing":"— non vérifié");var redir=p.website_redirect_url?(" → redirige vers "+p.website_redirect_url.slice(0,60)):"";var whyLine=(opp.level==="LOW"&&p.website_status==="ACTIVE")?"Site actif détecté — aucune opportunité de présence numérique évidente.":"Le domaine semble enregistré, mais aucun site web actif n'a été détecté lors de la dernière vérification. Cela peut représenter une opportunité de présence numérique, sous réserve d'une vérification manuelle.";return "<h4>🌐 WEBSITE INTELLIGENCE</h4><div class=\"why\"><b>Website</b><br>"+(p.website_url||p.website||"—")+"<br><br><b>Website Status</b><br>"+wiBadgeSite(p)+"<br><br><b>Domain Status</b><br>"+wiBadgeDomain(p)+domSrc+"<br><br><b>HTTPS</b><br>"+httpsLine+"<br><br><b>DNS</b><br>"+dnsLine+"<br><br><b>HTTP Status</b><br>"+(p.website_http_status||"—")+redir+"<br><br><b>Last checked</b><br>"+(p.website_last_checked||"jamais vérifié")+"<br><br><b>Confidence</b><br>site "+p.website_confidence+"% • domaine "+p.domain_confidence+"%<br><br><b>Digital Opportunity : "+opp.level+"</b><br><small>"+opp.why+" — observation technique, vérification manuelle recommandée.</small></div><div class=\"rowb\"><button id=\"wRecheck\">🔄 Recheck Website</button></div><h4>WHY THIS MAY BE AN OPPORTUNITY</h4><p><i>"+whyLine+"</i></p>";}
window.WebIntel={settings:wiSettings,ensure:wiEnsure,badgeSite:wiBadgeSite,badgeDomain:wiBadgeDomain,digitalOpp:wiDigitalOpp,checkDomain:wiCheckDomain,checkProspect:wiCheckProspect,bulkCheck:wiBulkCheck,parseFilter:wiParseFilter,match:wiMatch,cleanDomain:wiCleanDomain,prospectDomain:wiProspectDomain,drawerHTML:wiDrawerHTML};
